{% set name = "ubermag" %}
{% set version = "2025.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a4c71d9480bfe16e3e7c1fa395820873fb17edbb17811f8d2959dd0b4871acab

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - jupyterlab >=3.0
    - discretisedfield ==0.92.0
    - mag2exp ==0.64.0
    - micromagneticdata ==0.66.0
    - micromagneticmodel ==0.65.0
    - micromagnetictests ==0.64.0
    - mumax3c ==0.4.0
    - oommfc ==0.66.0
    - ubermagtable ==0.62.0
    - ubermagutil ==0.64.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - ubermag

  commands:
    # - python -c "import sys; import ubermag; sys.exit(ubermag.test())"  # fails with pyvista tests
    # instead: run only tests of metapackage
    - pytest -v $(python -c "from pathlib import Path; import ubermag.tests; print(Path(ubermag.tests.__file__).parent)")

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Meta package for the Ubermag project.
  doc_url: https://ubermag.github.io/documentation/ubermag.html
  dev_url: https://github.com/ubermag/ubermag

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
