{% set name = "ubermag" %}
{% set version = "0.1.1" %}
{% set sha256 = "428d206c93644f570287e6b0e21daa745174dfbd27f2a11757bbcb1e30f45a72" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: pip install --no-deps . -vvv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - oommfc
    - pytest

test:
  imports:
    - ubermag

  commands:
    - python -c "import sys; import ubermag as um; sys.exit(um.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-clause
  summary: A Python meta package for the Ubermag project.
  license_family: BSD
  license_file: LICENSE

  description: |
    `ubermag` is a Python meta package of the Ubermag project.
    It is available on all major operating systems (Windows, MacOS, Linux) and requires Python 3.6 or higher.
  doc_url: http://ubermag.readthedocs.io
  dev_url: https://github.com/ubermag/ubermag

extra:
  recipe-maintainers:
    - marijanbeg
