{% set name = "ubermag" %}
{% set version = "0.21" %}
{% set sha256 = "ec733d9c7d58d73fd43200e6a5d595fa4c80728bbf64907da02efda5d451fdba" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - oommfc ==0.8.20
    - micromagneticdata ==0.3

test:
  imports:
    - ubermag

  commands:
    - python -c "import sys; import ubermag as um; sys.exit(um.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Meta package for Ubermag project.
  doc_url: http://ubermag.readthedocs.io
  dev_url: https://github.com/ubermag/ubermag

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
