{% set name = "ubermag" %}
{% set version = "0.40" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6f740d978b41f5ce9fdd19106886dcff60915fff38dededda0980e363f1e27a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - oommfc ==0.8.25
    - micromagneticdata ==0.3.2

test:
  imports:
    - ubermag

  commands:
    - python -c "import sys; import ubermag; sys.exit(ubermag.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Meta package for the Ubermag project.
  doc_url: http://ubermag.readthedocs.io
  dev_url: https://github.com/ubermag/ubermag

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
