{% set name = "ubermag" %}
{% set version = "0.65.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad2d9c23aea5f2e9ac0df1f1a9fca923f6481bdfa193034f123ad4002da119e5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - discretisedfield ==0.63.0
    - mag2exp ==0.62.0
    - micromagneticdata ==0.63.0
    - micromagneticmodel ==0.62.0
    - micromagnetictests ==0.62.0
    - mumax3c ==0.1
    - oommfc ==0.63.0
    - ubermagtable ==0.61.1
    - ubermagutil ==0.63.0

test:
  imports:
    - ubermag

  commands:
    - python -c "import sys; import ubermag; sys.exit(ubermag.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Meta package for the Ubermag project.
  doc_url: https://ubermag.github.io/documentation/ubermag.html
  dev_url: https://github.com/ubermag/ubermag

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
