{% set name = "ubermag" %}
{% set version = "0.25" %}
{% set sha256 = "f1f12ecd7019805471e6e2a3cd5426f4b938c0f5177d19f12ff70dc98ff9546a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - oommfc ==0.8.24
    - micromagneticdata ==0.3.1

test:
  imports:
    - ubermag

  commands:
    - python -c "import sys; import ubermag as um; sys.exit(um.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Meta package for Ubermag project.
  doc_url: http://ubermag.readthedocs.io
  dev_url: https://github.com/ubermag/ubermag

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
