{% set name = "ubermag" %}
{% set version = "0.61.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3cf728cc7064c4ecca92ee0c63a340858484dc5081c69fb9b23802f42e2d503

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - discretisedfield ==0.61.0
    - mag2exp ==0.61.0
    - micromagneticdata ==0.61.0
    - micromagneticmodel ==0.61.0
    - micromagnetictests ==0.61.2
    - oommfc ==0.61.1
    - ubermagtable ==0.61.0
    - ubermagutil ==0.61.0

test:
  imports:
    - ubermag

  commands:
    - python -c "import sys; import ubermag; sys.exit(ubermag.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Meta package for the Ubermag project.
  doc_url: https://ubermag.github.io/documentation/ubermag.html
  dev_url: https://github.com/ubermag/ubermag

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
