travis:
  secure:
    BINSTAR_TOKEN: cJCqolAl8adwOutb/mEVmUBh7DgK0w7pIFijLLwG2N4wLvtuPeXF+iRQYeaFdwns+cEpNJqvK4oR/S6huZipthPLvBt3BptG28BwfGdsCGBRnIHTMl4qKwmowc6v6y4rWqLH24G1sTMdC4+qOYP/NqMbKVMyfk7GsLD9OkPoO5KxF7Vip4uXk6oWfL/KkVJaglkOH8X9ubST6DHlHH376QTm/cOf5jupg3w/n9pv0L+4AuvfOPi27WYUXOXo87keuh6lcLvB6Am7pmHW/lrwMi8njKOeSmzRTfgkrQumHskiPnjfygFm6XlI6/wcUa0gIoZmSOrgfGvvE6jzB11lpoivQ6WZK9T5qOwzhg7u8oEF5alT4vCUqQXfoQM2Hm//t+xbTjpstGgP2z610Ib+mPeVfj1ZJKQZAbfGGPbgSBg+7G0oeigWTpyZyfUqmId4RtBH43P6tMNreF96gE1bC67JOQmjPzr5601kVhR1V/fcrI6IfEWpP/GsUcG7vzttcSm5LOOuQhuhMSWjQpwMFM1HG6sktK7p5/akjofNDg7WiLrautInfP2W3Br5SFpBNx/FwdSmVH+7/YQ5BjMAhOa0ltQYMuHCW4vpM1AMmv01drPhpSNEQTxKd+o/uoenZRXSXBqPr7QD7oz/SXsPoPkLhKDQYsmVNe7RlWfH0yg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
