travis:
  secure:
    BINSTAR_TOKEN: dstOXdhyTCnJvSfkoIuSQSFk6TPgknvjJ3oYN0FYimg5Vu3pi4py63q+bjZ1AP8qtc22AS3YboRVlSgBmkUfWRiEP/6kgwB9x2mrURosxZcvqZZp4G9o9oXkl9ukqTpxfnvPePq2HhvSGi1zh137L88HbqQbn8rHjc8vG8e6E0Q8ScF0InpXrLHtJUbj+JeWIkRMmhRTRQ3jVDjio7RXHc4d02bvSPU2ANY6mysNf9x0XePuREoZ4P70hsjnOe41dmdoMZ9jQM0Mjvs+3aZwTWc3pfarvnZKDY/Y1feC4hHS1umAJ3DY+WOoEtHDH2omoaJVXrTvP1AbvaM5sB6fhus30ra41f6h0Ud1++X4ClBhCAyKc57ho4Pe8NMFK+vYnUAw3st9HjJlJtLeyrj/OFhl/dl7apGg4x8PNRxVY/SsGQNlE+VTujPdt2BB9f+VoGc7iW5HZGwv5gsjpTdzLuLSJ1aqlipgejzoTAQMDWT6Y96RSRPrNz+0ekUqdO0LiDCsDJIQsWz4PzgVAbH60ekZg8Kx1WlpmFDM+uTTI3GRiMCW/mCpuIZLcG2vM+3A43dTLTq0P+T8x/aLMJF0v4EjbJRzMgLkD0gOe5P+UTiB/ARMmT+FpmUgxt5XP3O7VhPC+hNjwiIAvv8+NfqeIGvumPu0XjYUT1fCKbY4hOc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
